var db = [  
         
  ["水",474,false,"shuǐ","level, water"],
  ["木",401,false,"mù","to cover, tree"],
  ["艸",395,false,"cǎo","grass, herbaceous plants"],
  ["言",287,false,"yán","to speak directly"],
  ["糸",286,false,"mì","a thin thread"],
  ["手",257,false,"shǒu","fist, hand"],
  ["人",256,false,"rén","the worthiest being on earth, man"],
  ["金",252,false,"jīn","metal"],
  ["心",232,false,"xīn","the heart"],
  ["女",208,false,"nǚ","the one going to where she belongs, wife, daughter"],
  ["口",170,false,"kǒu","mouth"],
  ["虫",147,false,"huǐ","worm, insect"],
  ["邑",136,false,"yì","polity, state"],
  ["土",133,false,"tǔ","earth, soil"],
  ["肉",132,false,"ròu","a large piece of meat"],
  ["馬",119,false,"mǎ","martial animal, horse"],
  ["玉",118,false,"yù","jade"],
  ["鳥",117,false,"diǎo","a long-tailed bird"],
  ["辵",115,false,"chuò","going once, and halting once"],
  ["衣",115,false,"yī","to rely on, clothes"],
  ["火",106,false,"huǒ","to destroy, fire"],
  ["車",100,false,"chē","a cart, a vehicle"],
  ["魚",99,false,"yú","fish"],
  ["疒",90,false,"nè","to lay down, to be sick"],
  ["目",84,false,"mù","eye"],
  ["頁",83,false,"yè","head"],
  ["禾",80,false,"hé","grain plant"],
  ["犬",79,false,"quǎn","dog, hound"],
  ["貝",74,false,"bèi","shell"],
  ["日",74,false,"rì","fruit, fulfilment, the sun"],
  ["足",71,false,"zú","foot"],
  ["門",70,false,"mén","where news are heard, door"],
  ["宀",63,false,"mián","roofs mutually covering"],
  ["攴",62,false,"pū","slight beat"],
  ["示",61,false,"shì","religious matters, what Heaven sends down"],
  ["刀",56,false,"dāo","weapon, sword"],
  ["山",52,false,"shān","to exalt, a mountain"],
  ["巾",50,false,"jīn","silken girdle"],
  ["广",47,false,"ān","house with a high roof structure"],
  ["穴",46,false,"xué","cave dwelling"],
  ["欠",46,false,"qiàn","to open the mouth wide and let breath coming out"],
  ["石",46,false,"shí","mountain stone"],
  ["酉",46,false,"yǒu","the fruits have reached ripeness, tenth of the Terrestrial Branches"],
  ["力",42,false,"lì","muscle, power, force"],
  ["革",40,false,"gé","processed animal skin"],
  ["走",38,false,"zǒu","to walk"],
  ["隹",36,false,"zhuī","short-tailed bird"],
  ["耳",36,false,"ěr","the ear"],
  ["羽",33,false,"yǔ","wing feathers"],
  ["牛",32,false,"niú","cattle"],
  ["齒",32,false,"chǐ","teeth"],
  ["雨",32,false,"yǔ","rain"],
  ["黑",30,false,"hēi","colour of soot, black"],
  ["彳",29,false,"chì","small step"],
  ["見",29,false,"jiàn","to see, to look"],
  ["角",28,false,"jué","horn of an animal"],
  ["田",28,false,"tián","to spread out, field"],
  ["囗",27,false,"wéi","encirclement"],
  ["网",26,false,"wǎng","fishing net"],
  ["弓",26,false,"gōng","to reach that far away, a bow"],
  ["歺",25,false,"null","null"],
  ["米",25,false,"mǐ","the fruit of grain"],
  ["鹿",24,false,"lù","deer"],
  ["戈",24,false,"gē","halberd"],
  ["骨",23,false,"gǔ","bones"],
  ["髟",23,false,"biāo","long hair hanging down"],
  ["又",21,false,"yòu","(right) hand"],
  ["豕",21,false,"shǐ","pig"],
  ["豸",21,false,"zhì","marten and similar animals with a long body"],
  ["䖵",21,false,"kūn","insects and worms"],
  ["㫃",19,false,"yǎn","weaving streamers"],
  ["羊",18,false,"yáng","goat, sheep"],
  ["匚",18,false,"fāng","a container vessel"],
  ["瓦",18,false,"wǎ","earthenware, ceramics, tile"],
  ["厂",17,false,"hàn","mountain cliff shielding houses"],
  ["仌",17,false,"null","null"],
  ["尸",16,false,"shī","to exhibit, body"],
  ["子",14,false,"zǐ","rich fruits, son, children, first of the Terrestrial Branches"],
  ["殳",14,false,"shū","to separate persons with a spear"],
  ["黽",14,false,"mǐn","frog"],
  ["斤",14,false,"jīn","to cut trees, an axe"],
  ["風",13,false,"fēng","wind"],
  ["止",12,false,"zhǐ","base"],
  ["舟",12,false,"zhōu","boat, ship"],
  ["立",12,false,"lì","to stand"],
  ["老",11,false,"lǎo","an old person"],
  ["勹",11,false,"bāo","to embrace, to hold"],
  ["鼠",11,false,"shǔ","animals living in holes, rats"],
  ["斗",11,false,"dǒu","ten sheng (litres), a volume measure"],
  ["行",10,false,"xíng","to walk"],
  ["䰜",10,false,"lì","cooking pot"],
  ["林",10,false,"lín","forest"],
  ["白",10,false,"zì (!)","nose"],
  ["卩",10,false,"jié","seal"],
  ["大",10,false,"tài","great (note: top position)"],
  ["戶",10,false,"hù","to cover, house"],
  ["八",9,false,"bā","to separate, number eight"],
  ["鬼",9,false,"guǐ","what a man turn to in the end, a ghost"],
  ["赤",9,false,"chì","colour of the south, red"],
  ["月",8,false,"yuè","a lack of sth., the moon"],
  ["夕",8,false,"xī","evening"],
  ["片",8,false,"piàn","half a trunk, split wood"],
  ["匕",8,false,"bǐ","to compare"],
  ["鬲",7,false,"lí","a kind of tripod"],
  ["卜",7,false,"bǔ","divination crack on tortoise plastron"],
  ["十",7,false,"shí","the full number, ten"],
  ["寸",7,false,"cùn","length unit, ten fen"],
  ["鬥",7,false,"dòu","to engage with weapons"],
  ["晶",7,false,"jīng","brilliant"],
  ["儿",7,false,"ér","a man of a kind sense"],
  ["彡",7,false,"xiǎn","hair, decoration of paintings, or patterns"],
  ["幸",7,false,"xìng","an instrument to intimidate people"],
  ["尣",7,false,"wāng","a bent leg"],
  ["二",7,false,"èr","double, two"],
  ["辛",7,false,"xīn","penetrating flavour of autumn, eighth of the Celestial Stems"],
  ["屮",6,false,"chè","sprout"],
  ["是",6,false,"shì","direct"],
  ["爪",6,false,"zhǎo","to grasp"],
  ["音",6,false,"yīn","tone, sound"],
  ["㗊",6,false,"jí","many mouths"],
  ["耒",6,false,"lěi","the curved beam of a hand plow"],
  ["萑",6,false,"null","null"],
  ["生",6,false,"shēng","to grow"],
  ["臼",6,false,"jiù","mortar"],
  ["㐺",6,false,"yín","several persons standing together"],
  ["丘",6,false,"qiū","natural hill"],
  ["長",6,false,"cháng","long and far away"],
  ["屵",6,false,"àn","a high cliff"],
  ["囪",6,false,"cōng","roof window"],
  ["夲",6,false,"běn","to hasten forward"],
  ["川",6,false,"chuān","broadly streaming water"],
  ["亾",6,false,"wáng","to escape, to leave, to die"],
  ["至",6,false,"zhì","a bird arriving at the ground"],
  ["禸",6,false,"róu","the foot of an animal treads upon the earth"],
  ["一",5,false,"yī","one, origin"],
  ["茻",5,false,"mǎng","thicket"],
  ["士",5,false,"shì","servant, minister"],
  ["冊",5,false,"null","null"],
  ["釆",5,false,"biàn","to distinguish"],
  ["吅",5,false,"xuān","to shout in alarm"],
  ["誩",5,false,"jìng","to quarrel"],
  ["聿",5,false,"yù","writing tool"],
  ["舁",5,false,"yú","to lift jointly"],
  ["丵",5,false,"zhuó","densely growing grass"],
  ["臤",5,false,"qiān","solid"],
  ["钗",5,false,"null","null"],
  ["奞",5,false,"xùn","a long-winged bird raises"],
  ["刃",5,false,"rèn","blade"],
  ["烏",5,false,"wū","a bird respectful towards its progenitors, a crow"],
  ["鼻",5,false,"bí","to breathe"],
  ["華",5,false,"huá","blossoming, richly flowering"],
  ["鼎",5,false,"dǐng","a tripod with earhandles"],
  ["冃",5,false,"mào","head scarf worn by children and the southern barbarians"],
  ["㝱",5,false,"mèng","to dream"],
  ["毛",5,false,"máo","hair of any kind"],
  ["夰",5,false,"gǎo","to release"],
  ["绊",5,false,"null","null"],
  ["炎",5,false,"yán","a fire's brightness is raising high"],
  ["谷",5,false,"gǔ","river valley"],
  ["鹽",5,false,"yán","salt"],
  ["匸",5,false,"xì","to stand inclined to one side"],
  ["劦",5,false,"xié","joint forces"],
  ["丄",4,false,"shàng","high above"],
  ["龠",4,false,"yuè","flute"],
  ["用",4,false,"yòng","do-able"],
  ["句",4,false,"gōu","to bend, a hook"],
  ["皮",4,false,"pí","animal skin"],
  ["畫",4,false,"huà","defined borderline"],
  ["殺",4,false,"shā","to kill"],
  ["宮",4,false,"gōng","large building"],
  ["黍",4,false,"shǔ","glutinous millet"],
  ["襾",4,false,"yà","cover, envelope"],
  ["朿",4,false,"cì","thorns of a tree"],
  ["毌",4,false,"guàn","to penetrate and lock together"],
  ["黹",4,false,"zhǐ","embroidered cloth"],
  ["尾",4,false,"wěi","small, tail"],
  ["履",4,false,"lǚ","footwear"],
  ["兂",4,false,"zān","hairpin"],
  ["文",4,false,"wén","crossing pattern"],
  ["思",4,false,"sī","to embrace thoughts"],
  ["夨",4,false,"cè","a bent head"],
  ["兔",4,false,"tù","hare, rabbit"],
  ["焱",4,false,"yàn","sparks"],
  ["永",4,false,"0","eternally flowing"],
  ["丿",4,false,"piě","brush stroke from the right"],
  ["鹵",4,false,"lǔ","a salt-producing region in the west"],
  ["黃",4,false,"huáng","the colour of the soil, yellow"],
  ["素",4,false,"sù","white, uncoloured silk"],
  ["几",4,false,"jī","to squat, a low table"],
  ["乙",4,false,"yǐ","sprouts coming out of the earth, second of the Celestial Stems"],
  ["王",3,false,"wáng","king, the one towards whom all people hurry"],
  ["小",3,false,"xiǎo","small"],
  ["步",3,false,"bù","to go"],
  ["哭",3,false,"kū","to weep"],
  ["廴",3,false,"yìn","to walk a long distance"],
  ["癶",3,false,"bō","blocked feet (note: top position)"],
  ["告",3,false,"gào","to mark a dangerous bull"],
  ["半",3,false,"bàn","things divided in the middle"],
  ["犛",3,false,"máo","Tibetan yak"],
  ["教",3,false,"jiào","to instruct and to imitate"],
  ["臣",3,false,"chén","entrusted with an official task, a minister"],
  ["異",3,false,"yì","separate, different"],
  ["菐",3,false,"pú","petty and mulitudineous"],
  ["隶",3,false,"lì","to reach and catch"],
  ["死",3,false,"sǐ","to expire, to die"],
  ["雥",3,false,"zá","a flock of birds"],
  ["叀",3,false,"zhuān","attentive and prudent"],
  ["予",3,false,"yú","to present to sbd."],
  ["冓",3,false,"gòu","to exchange and accumulate materials"],
  ["雔",3,false,"chóu","a pair of birds"],
  ["帀",3,false,"zā","to encircle"],
  ["出",3,false,"chū","to advance"],
  ["㯻",3,false,"hùn","to tie to a bundle"],
  ["束",3,false,"shù","to bind"],
  ["員",3,false,"yuán","a certain number of sth."],
  ["朙",3,false,"null","null"],
  ["有",3,false,"yǒu","what should better not occur"],
  ["帛",3,false,"bó","silken cloth"],
  ["瓜",3,false,"guā","melon, gourd, cucumber"],
  ["冖",3,false,"mì","cover"],
  ["韭",3,false,"jiǔ","leek"],
  ["尗",3,false,"shú","bean"],
  ["呂",3,false,"lǚ","dorsal spine"],
  ["从",3,false,"cóng","to obey, to follow"],
  ["方",3,false,"fāng","boats tied together"],
  ["秃",3,false,"null","null"],
  ["臥",3,false,"wò","to rest"],
  ["色",3,false,"sè","colour or mood on the face"],
  ["司",3,false,"sī","official outside the court"],
  ["包",3,false,"bāo","a pregnant woman"],
  ["彣",3,false,"wén","coloured pattern"],
  ["須",3,false,"xū","facial hair, beard"],
  ["厶",3,false,"sī","intrigant, evil"],
  ["甶",3,false,"fú","head of a ghost"],
  ["夫",3,false,"fū","husband"],
  ["交",3,false,"jiāo","crossed legs"],
  ["夭",3,false,"yāo","bent, twisted"],
  ["竝",3,false,"null","null"],
  ["囟",3,false,"xìn","fontanelle of the cranium"],
  ["非",3,false,"fēi","to oppose"],
  ["龍",3,false,"lóng","the master of the scaly animals, dragon"],
  ["雲",3,false,"yún","the exhalation of mountains and rivers, clouds"],
  ["瀕",3,false,"bīn","the bank of a river"],
  ["我",3,false,"wǒ","I, me"],
  ["乚",3,false,"yǐ","a black bird, swallow"],
  ["琴",3,false,"qín","to halt the improper by music, a zither"],
  ["弦",3,false,"xián","a bowstring"],
  ["弜",3,false,"jiàng","strong"],
  ["甾",3,false,"zī","a mug (dialect word)"],
  ["男",3,false,"nán","husband, man"],
  ["里",3,false,"lǐ","living place, village"],
  ["蟲",3,false,"chóng","crawling animals"],
  ["申",3,false,"shēn","the yin spirit is reaching out again, ninth of the Terrestrial Branches"],
  ["了",3,false,"liǎo","to cross legs while walking"],
  ["孨",3,false,"zhuǎn","to take care"],
  ["丨",2,false,"gǔn","penetrating vertically"],
  ["三",2,false,"sān","trinity of Heaven, Earth and Man"],
  ["玨",2,false,"jué","double jade"],
  ["蓐",2,false,"rù","perennial plants"],
  ["正",2,false,"zhèng","correct"],
  ["品",2,false,"pǐn","masses, manifold"],
  ["牙",2,false,"yá","molar teeth"],
  ["此",2,false,"cǐ","to stop"],
  ["古",2,false,"gǔ","ancient times"],
  ["共",2,false,"gòng","together"],
  ["㕯",2,false,"nè","clumsy speech"],
  ["史",2,false,"shǐ","official scribe"],
  ["卅",2,false,"sà","thirty"],
  ["㸚",2,false,"lǐ","to exchange several times"],
  ["支",2,false,"zhī","to strip off leaves from bamboo twigs"],
  ["爨",2,false,"cuàn","to cook (dialect of the region of Qi)"],
  ["䇂",2,false,"qiān","crime, fault"],
  ["爻",2,false,"yáo","to exchange"],
  ["丩",2,false,"jiū","to intertwine"],
  ["丮",2,false,"jǐ","to hold"],
  ["自",2,false,"zì","nose"],
  ["玄",2,false,"xuán","dark and far away"],
  ["眉",2,false,"méi","eyebrow"],
  ["習",2,false,"xí","a flock of birds flying"],
  ["冎",2,false,"guǎ","to cut off a man's flesh and store his bones"],
  ["幺",2,false,"yāo","small, young"],
  ["盾",2,false,"dùn","shield"],
  ["筋",2,false,"jīn","the power of flesh, muscles"],
  ["瞿",2,false,"qú","the frightening sight of falcons"],
  ["皕",2,false,"bì","two hundred"],
  ["羴",2,false,"shān","a goat's smell"],
  ["青",2,false,"null","null"],
  ["叒",2,false,"ruò","a miraculous tree that comes out at dawn, mulberry"],
  ["旦",2,false,"dàn","dawn"],
  ["秝",2,false,"lì","rare and suitable"],
  ["多",2,false,"duō","endless repetition"],
  ["香",2,false,"xiāng","fragrant herbs"],
  ["凶",2,false,"xiōng","bad omen"],
  ["囧",2,false,"jiǒng","interlocking windows illuminate the room"],
  ["冥",2,false,"míng","dark"],
  ["㒳",2,false,"liǎng","again, two times"],
  ["麻",2,false,"má","hemp"],
  ["瓠",2,false,"hù","calabash"],
  ["朩",2,false,"pìn","the skin of hemp stalks"],
  ["毇",2,false,"huǐ","to bruise grain"],
  ["巿",2,false,"fú","knee cover, apron"],
  ["北",2,false,"běi","to turn away from sby., north"],
  ["比",2,false,"bǐ","near, close"],
  ["身",2,false,"shēn","the body"],
  ["裘",2,false,"qiú","leather clothes"],
  ["重",2,false,"zhòng","thick, heavy"],
  ["尺",2,false,"chǐ","ten inches"],
  ["先",2,false,"xiān","to be the first"],
  ["皃",2,false,"mào","appearance"],
  ["旡",2,false,"jì","the gullet is obstructed"],
  ["㳄",2,false,"xián","saliva is dripping out of the mouth"],
  ["㱃",2,false,"yǐn","to drink"],
  ["冄",2,false,"rǎn","hair hanging down"],
  ["而",2,false,"ér","beard"],
  ["象",2,false,"xiàng","elephant"],
  ["首",2,false,"shǒu","head"],
  ["茍",2,false,"jì","to alert, to admonish oneself"],
  ["面",2,false,"miàn","face"],
  ["勿",2,false,"wù","banner of a province"],
  ["嵬",2,false,"wéi","high, but not even"],
  ["丸",2,false,"wán","round objects"],
  ["彑",2,false,"jì","a pig's head"],
  ["屾",2,false,"shēn","two mountains"],
  ["熊",2,false,"xióng","bear"],
  ["壹",2,false,"yī","non-leaking can"],
  ["炙",2,false,"zhì","to roast meat"],
  ["㹜",2,false,"yín","quarreling dogs"],
  ["奢",2,false,"shē","to broaden, to extent"],
  ["惢",2,false,"suǒ","doubts, thoughts"],
  ["壺",2,false,"hú","a round vessel"],
  ["沝",2,false,"zhuǐ","two waters"],
  ["飛",2,false,"fēi","to fly"],
  ["灥",2,false,"xún","three sources"],
  ["巜",2,false,"kuài","the sound of gurgling water"],
  ["民",2,false,"mín","to sprout in masses, the people"],
  ["西",2,false,"xī","a bird's nest, west"],
  ["氏",2,false,"zhī","a mountain cliff breaking down"],
  ["戉",2,false,"yuè","axe"],
  ["毋",2,false,"wú","to stop sbdy."],
  ["系",2,false,"xì","to tie together"],
  ["絲",2,false,"sī","raw silk"],
  ["垚",2,false,"yáo","high spot of earth"],
  ["堇",2,false,"jǐn","loamy soil"],
  ["卵",2,false,"luǎn","egg"],
  ["畕",2,false,"jiāng","neighbouring fields"],
  ["巳",2,false,"sì","yang has come out, while yin is bent down, sixth of the Terrestrial Branches"],
  ["戊",2,false,"wù","moving towards the centre of the year, fifth of the Celestial Stems"],
  ["辰",2,false,"chén","to shake the earth, fifth of the Terrestrial Branches"],
  ["且",2,false,"qiě","to put down, a dish"],
  ["九",2,false,"jiǔ","the change of the yang, nine"],
  ["四",2,false,"sì","the yin number, four"],
  ["己",2,false,"jǐ","the fruits are moved towards the granaries, sixth of the Celestial Stems"],
  ["丑",2,false,"chǒu","to knot, nature is impeded in winter, second of the Terrestrial Branches"],
  ["午",2,false,"wǔ","yin is reverting against yang in autumn, seventh of the Terrestrial Branches"],
  ["矛",2,false,"máo","a long spear"],
  ["辡",2,false,"biàn","plaintiff and defendant"],
  ["叕",2,false,"jué","to intertwine"],
  ["嘼",2,false,"xù","cattle, beast, animal"],
  ["厽",2,false,"lěi","a piled-up earthen wall"],
  ["气",1,false,"qì","cloudy or misty air"],
  ["㢟",1,false,"chān","to walk hesitatingly"],
  ["疋",1,false,"shū","foot"],
  ["干",1,false,"gān","to violate"],
  ["舌",1,false,"shé","tongue"],
  ["放",1,false,"fàng","to get rid of sth."],
  ["丯",1,false,"null","null"],
  ["㓞",1,false,"qì","to incise skilfully"],
  ["高",1,false,"gāo","lofty"],
  ["來",1,false,"lái","a kind of ominous grain"],
  ["矢",1,false,"shǐ","arrow or bolt"],
  ["箕",1,false,"jī","winnowing basket"],
  ["夊",1,false,"suī","to walk slowly, dragging a leg (note: bottom position)"],
  ["亏",1,false,"kuī","same as 於 (crow, later a prepositional verb)"],
  ["壴",1,false,"zhù","to arrange musical instruments"],
  ["皿",1,false,"mǐn","a dish"],
  ["皀",1,false,"bī","the odour of grain"],
  ["入",1,false,"rù","to enter"],
  ["可",1,false,"kě","to allow"],
  ["之",1,false,"zhī","to grow, to come out"],
  ["才",1,false,"cái","shoot of a tree"],
  ["巢",1,false,"cháo","bird's nest"],
  ["稽",1,false,"jī","to rest"],
  ["東",1,false,"dōng","to move, the east"],
  ["乇",1,false,"zhé","leaves"],
  ["桼",1,false,"qī","sap of a tree"],
  ["克",1,false,"kè","to shoulder"],
  ["齊",1,false,"qí","the ears of grain leveled on the same height"],
  ["㡀",1,false,"bì","worn-out clothes"],
  ["耑",1,false,"duān","the tip of sprouts"],
  ["倝",1,false,"gàn","the morning sun"],
  ["彔",1,false,"lù","to split wood"],
  ["㐆",1,false,"yǐn","to rely on sth."],
  ["兄",1,false,"xiōng","the older brother"],
  ["毳",1,false,"cuì","thin hair of animals"],
  ["覞",1,false,"yào","to look at each other"],
  ["易",1,false,"yì","lizard"],
  ["㣇",1,false,"yì","wild animal with long hair"],
  ["印",1,false,"yìn","seal of the ruler"],
  ["危",1,false,"wēi","to stand on a high point and be frightened"],
  ["辟",1,false,"bì","a standard, a rule"],
  ["卮",1,false,"zhī","wine jar"],
  ["豚",1,false,"tún","piglet"],
  ["丏",1,false,"miǎn","not able to see"],
  ["亦",1,false,"yì","a man's armpit"],
  ["能",1,false,"néng","a kind of bear"],
  ["亢",1,false,"kàng","the neck"],
  ["㲋",1,false,"chuò","hare-like animal with grey hair"],
  ["麤",1,false,"cū","travelling far"],
  ["萈",1,false,"huán","mountain goat with small horns"],
  ["燕",1,false,"yàn","a black bird, swallow"],
  ["泉",1,false,"quán","a source"],
  ["卂",1,false,"xùn","to fly quickly"],
  ["く",1,false,"quǎn","small creek flowing"],
  ["不",1,false,"bù","a bird flies high and does not come back"],
  ["乀",1,false,"yí","to move"],
  ["曲",1,false,"qū","a container"],
  ["氐",1,false,"dī","to reach, to arrive"],
  ["亅",1,false,"jué","hook, reversal"],
  ["它",1,false,"tā","snake"],
  ["率",1,false,"shuài","net of a bird-catcher"],
  ["龜",1,false,"guī","an old animal, tortoise"],
  ["丁",1,false,"dīng","plants are growing in summer, fourth of the Celestial Stems"],
  ["五",1,false,"wǔ","the Five Agents"],
  ["甲",1,false,"jiǎ","in spring, buds open their outer shell, armour, crust, first of the Celestial Stems"],
  ["七",1,false,"qī","the correct yang number, seven"],
  ["酋",1,false,"qiú","a long brewery process"],
  ["六",1,false,"liù","the changing number of the Book of Changes, six"],
  ["未",1,false,"wèi","full flavour, eighth of the Terrestrial Branches"],
  ["庚",1,false,"gēng","ripe fruits in autumn, seventh of the Celestial Stems"],
  ["亥",1,false,"hài","the yang spirit has gone down to the roots, twelfth of the Terrestrial Branches"],
  ["壬",1,false,"tǐng (!)","good"],
  ["癸",1,false,"guǐ","to survey barren fields, tenth of the Celestial Stems"],
  ["巴",1,false,"bā","a snake"],
  ["寅",1,false,"yín","the yang spirit is driven down to the Yellow Sources, third of the Terrestrial Branches"],
  ["丙",1,false,"bǐng","brilliance in spring, third of the Celestial Stems"],
  ["戌",1,false,"xū","to extinguish the yang spirit, eleventh of the Terrestrial Branches"],
  ["勺",1,false,"sháo","to ladle"],
  ["亞",1,false,"yā","bad, ugly"],
  ["戼",1,false,"yín","to penetrate the earth in spring, fourth of the Terrestrial Branches"],
  ["幵",1,false,"jiān","even, leveled"],
      ]
      
      // word = [];
      // for (var i in db) {
      //   word.push([db[i]["word"], db[i]["fre"],db[i]["3"],db[i]["4"],db[i]["5"]])
      // }
      // console.log(word)
      

var mark = 0;
var wordCloud = new B2wordcloud(document.getElementById("radical"), {
    // renderer: 'div',
    list: db,
    tooltip: {
        formatter: function(item) {
            return '<div>' + item[0] +"  "+ item[3] + '</div>' 
            + '<div>' + "Words number: "+ item[1] + '</div>'
            + '<div>' + "Meaning: "+ item[4] + '</div>'
        }
    },
    // hover: function(item) {
    //     console.log(item)
    // },
    
    "gridSize": 24, // 密集程度 数字越小越密集
    "weightFactor": 100, // 字体大小=原始大小*weightFactor
    "maxFontSize": 220, //最大字号
    "minFontSize": 36, //最小字号 
    "fontWeight": 'normal', //字体粗细
    "fontFamily": 'Times, serif', // 字体
    "color":'#EEE', // 字体颜色 'random-dark' 或者 'random-light'
    backgroundColor: '#333', // 背景颜色
    shadowColor: '#333',
    shadowOffsetX:3,
    shadowOffsetY:2,
    shadowBlur:4,
    "rotateRatio": 0,
    drawOutOfBound: false
    
})
          
          
          // window.addEventListener('resize', function() {
          //     wordCloud.resize()
          // })
